git:
    submodules: false
sudo: required
dist: trusty
language: cpp
script: 
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make && cd ..
  - make DESTDIR=$(pwd)/test test
python: 
  - "3.5"
before_script:
  - sudo add-apt-repository ppa:mc3man/trusty-media -y
  - sudo apt-get update
  - sudo apt-get -y -q install ffmpeg
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git clone https://github.com/pscholl/grt grt_master
  - cd grt_master/build
  - cmake  -DCMAKE_INSTALL_PREFIX:PATH=/usr . && sudo make install && cd ../../
  - git submodule update --init --remote dlib
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    - pythonxy-devel
    packages:
    - gcc-5
    - g++-5
    - clang
    - python3.5
    - libopenblas-dev
    - liblapack-dev
