sudo: true
language: cpp
script: make DESTDIR=$(pwd)/test test
before_script:
  - git clone https://github.com/pscholl/grt
  - cd grt/build
  - cmake . && sudo make install && cd ../../
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
