git:
    submodules: false
sudo: required
dist: trusty
language: cpp
script: make DESTDIR=$(pwd)/test test
python: 
  - "3.5"
before_script:
  - sudo add-apt-repository ppa:kirillshkrogalev/ffmpeg-next -y
  - sudo apt-get update
  - sudo apt-get -y -q install ffmpeg
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git clone https://github.com/pscholl/grt grt_master
  - cd grt_master/build
  - cmake  -DCMAKE_INSTALL_PREFIX:PATH=/usr . && sudo make install && cd ../../
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - pythonxy-devel
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - python3.5
